In [1]:
#re-practicing the numpy
# we will simulate data for 5 students and their scores in 4 subjects

In [2]:
import numpy as np
marks = np.array([
    [85, 92, 78, 90],  # Student 1
    [70, 88, 82, 85],  # Student 2
    [60, 75, 65, 70],  # Student 3
    [95, 98, 99, 97],  # Student 4
    [50, 45, 60, 55]   # Student 5
])

In [5]:
print("shape:",marks.shape)
print("total students:",marks.shape[0])
print("subjects:",marks.shape[1])

shape: (5, 4)
total students: 5
subjects: 4


In [6]:
print("average per subject:",np.mean(marks,axis=0))
print("maximum per subject:",np.max(marks,axis=0))
print("minimum per subject:",np.min(marks,axis=0))
print("standard deviation per subject:",np.std(marks,axis=0))

average per subject: [72.  79.6 76.8 79.4]
maximum per subject: [95 98 99 97]
minimum per subject: [50 45 60 55]
standard deviation per subject: [16.30950643 18.87432118 13.73171512 15.08111402]


In [7]:
total_marks = np.sum(marks, axis=1)
print("total marks of each student:", total_marks)

average_marks = np.mean(marks, axis=1)
print("average marks of each student:",average_marks)

total marks of each student: [345 325 270 389 210]
average marks of each student: [86.25 81.25 67.5  97.25 52.5 ]


In [10]:
top_student = np.argmax(total_marks)
print("top student is student",top_student + 1,"with",total_marks[top_student], "marks out of 400")

top student is student 4 with 389 marks out of 400


In [14]:
high_achievers = np.where(average_marks > 80)
print("student with average > 80:", high_achievers[0] + 1)

student with average > 80: [1 2 4]


In [15]:
normalized = (marks - np.min(marks))/(np.max(marks) - np.min(marks))
print("nrmalized marks:\n", normalized)


nrmalized marks:
 [[0.74074074 0.87037037 0.61111111 0.83333333]
 [0.46296296 0.7962963  0.68518519 0.74074074]
 [0.27777778 0.55555556 0.37037037 0.46296296]
 [0.92592593 0.98148148 1.         0.96296296]
 [0.09259259 0.         0.27777778 0.18518519]]


In [16]:
sorted_indices = np.argsort(total_marks)[::-1]
print("ranked student indices:", sorted_indices+1)

ranked student indices: [4 1 2 3 5]


In [17]:
for i in sorted_indices:
    print(f"student{i+1}- total: {total_marks[i]}, avg: {average_marks[i]: .2f}")

student4- total: 389, avg:  97.25
student1- total: 345, avg:  86.25
student2- total: 325, avg:  81.25
student3- total: 270, avg:  67.50
student5- total: 210, avg:  52.50
